#!/usr/bin/env bash
# This script checks the status of the school file
# Define the file name
file="school"
# Check if the file exists
if [[ -e "$file" ]]; then
  echo "school file exists"
  # Check if the file is a regular file
  if [[ -f "$file" ]]; then
    # Check if the file is empty
    if [[ ! -s "$file" ]]; then
      echo "school file is empty"
    else
      echo "school file is not empty"
    fi

    echo "school is a regular file"
  fi
  # Check if the file is a directory
  if [[ -d "$file" ]]; then
    # Check if the directory is empty
    if [[ -z "$(find "$file" -mindepth 1 -print -quit)" ]]; then
      echo "school file is empty"
    else
      echo "school file is not empty"
    fi
  fi
else
  echo "school file does not exist"
fi
