#!/usr/bin/env bash
# Script to display a list of currently running processes
# Use ps to list processes and format the output
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --sort=user | awk '
NR==1 { print "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND" }
NR>1 { printf "%-10s %-5s %-5s %-5s %-5s %-5s %-8s %-5s %-8s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11 }'
